using UnityEngine;

public class PinchGrabber : MonoBehaviour
{
    [Header("Hand References")]
    [Tooltip("Drag the Hand GameObject (the one that generates the skeleton) here.")]
    public Transform handRoot;

    [Header("Grab Mechanics")]
    [Tooltip("How close EACH fingertip must be to the marble's center to grab it (in meters).")]
    public float pinchGrabRadius = 0.015f; 
    
    [Tooltip("Distance between the two fingers required to trigger a release. Must be larger than pinchGrabRadius * 2.")]
    public float pinchReleaseDistance = 0.04f;
    
    [Tooltip("Assign a specific layer to your marbles to avoid grabbing other objects.")]
    public LayerMask marbleLayer;

    // Runtime assigned bones
    private Transform indexTip;
    private Transform thumbTip;
    private bool bonesInitialized = false;

    // State tracking
    private Rigidbody heldMarble;
    private bool canGrab = true; 
    
    // Momentum tracking variables (Rolling frame buffer)
    private Vector3[] positionHistory;
    private int historyIndex = 0;
    private const int HISTORY_SIZE = 5; 

    // Pre-allocated array for physics checks to eliminate garbage collection
    private Collider[] marbleColliders = new Collider[10];

    void Start()
    {
        positionHistory = new Vector3[HISTORY_SIZE];
    }

    void Update()
    {
        // Wait for the bones to be generated by the Oculus SDK
        if (!bonesInitialized)
        {
            TryInitializeBones();
            return; 
        }

        // Calculate finger separation once per frame to drive our state logic
        float fingerSeparation = Vector3.Distance(indexTip.position, thumbTip.position);

        if (heldMarble is null)
        {
            // 1. The "Open to Grab" Logic
            if (fingerSeparation > pinchGrabRadius * 2.5f) 
            {
                // Fingers are open wide enough to accept a marble
                canGrab = true; 
            } 
            else if (fingerSeparation < pinchGrabRadius * 1.2f) 
            {
                // Fingers are pinched closed on empty air
                canGrab = false; 
            }

            if (canGrab)
            {
                CheckForGrab();
            }
        }
        else
        {
            // We pass fingerSeparation here so we don't have to calculate distance twice
            CheckForRelease(fingerSeparation);
        }
    }

    void LateUpdate()
    {
        // 2. The Smoothness Fix
        // LateUpdate ensures we move the marble AFTER the hand skeleton has finished updating its position for this frame.
        if (heldMarble is not null)
        {
            UpdateHeldMarble();
        }
    }

    private void TryInitializeBones()
    {
        if (handRoot == null) return;

        if (indexTip == null) indexTip = FindFingertip(handRoot, "XRHand_IndexTip");
        if (thumbTip == null) thumbTip = FindFingertip(handRoot, "XRHand_ThumbTip");

        if (indexTip != null && thumbTip != null)
        {
            bonesInitialized = true;
        }
    }

    private Transform FindFingertip(Transform parent, string keyword)
    {
        foreach (Transform child in parent)
        {
            if (child.name == keyword)
            {
                return child;
            }
            
            Transform found = FindFingertip(child, keyword);
            if (found != null) return found;
        }
        return null;
    }

    private void CheckForGrab()
    {
        Vector3 midpoint = (indexTip.position + thumbTip.position) / 2f;
        
        // Use NonAlloc to fill our pre-existing array. It returns the number of objects found.
        int hitCount = Physics.OverlapSphereNonAlloc(midpoint, pinchGrabRadius * 2f, marbleColliders, marbleLayer);

        // Iterate only up to hitCount, ignoring the rest of the array
        for (int i = 0; i < hitCount; i++)
        {
            Collider col = marbleColliders[i];
            
            float distToIndex = Vector3.Distance(indexTip.position, col.transform.position);
            float distToThumb = Vector3.Distance(thumbTip.position, col.transform.position);

            if (distToIndex <= pinchGrabRadius && distToThumb <= pinchGrabRadius)
            {
                Rigidbody rb = col.GetComponent<Rigidbody>();
                if (rb is not null)
                {
                    Grab(rb);
                    break; 
                }
            }
        }
    }

    private void Grab(Rigidbody marbleRb)
    {
        heldMarble = marbleRb;
        heldMarble.isKinematic = true;
        canGrab = false; // Reset the state so we don't accidentally re-trigger logic

        Vector3 currentPos = (indexTip.position + thumbTip.position) / 2f;
        for (int i = 0; i < HISTORY_SIZE; i++)
        {
            positionHistory[i] = currentPos;
        }
    }

    private void UpdateHeldMarble()
    {
        Vector3 holdPosition = (indexTip.position + thumbTip.position) / 2f;
        heldMarble.position = holdPosition;

        positionHistory[historyIndex] = holdPosition;
        historyIndex = (historyIndex + 1) % HISTORY_SIZE;
    }

    private void CheckForRelease(float fingerSeparation)
    {
        if (fingerSeparation > pinchReleaseDistance)
        {
            Release();
        }
    }

    private void Release()
    {
        heldMarble.isKinematic = false;
        heldMarble.linearVelocity = CalculateThrowVelocity();
        heldMarble = null;
    }

    private Vector3 CalculateThrowVelocity()
    {
        int oldestIndex = historyIndex; 
        int newestIndex = (historyIndex - 1 + HISTORY_SIZE) % HISTORY_SIZE;

        Vector3 oldestPosition = positionHistory[oldestIndex];
        Vector3 newestPosition = positionHistory[newestIndex];

        float timeElapsed = Time.deltaTime * (HISTORY_SIZE - 1);

        if (timeElapsed > 0)
        {
            return (newestPosition - oldestPosition) / timeElapsed;
        }

        return Vector3.zero;
    }
}